source "https://rubygems.org"

gem "fastlane", "=2.120.0" # change the versoin to your favourite version or remove it for latest versoin
gem "cocoapods", "=1.6.1" # change the versoin to your favourite version or remove it for latest versoin