fastlane_version "2.120.0"

default_platform(:ios)

platform :ios do
  
  before_all do
    #ensure_git_branch(branch: 'branch_name')
    ensure_git_status_clean
    git_pull
  end

  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(type: 'development')
    match(type: 'appstore')
  end
  
  desc "Runs all the tests"
  lane :test do
    scan
  end
  
  desc 'Build the iOS application.'
  private_lane :build do
    match(type: 'appstore')
    build_number=latest_testflight_build_number + 1
    increment_build_number(build_number: build_number)
    gym(scheme: 'schema_name', project: 'path_to_xcodeproj')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    pilot
    commit_version_bump(message: 'Bump build')
    push_to_git_remote
  end

end
